config/routes.rb
Qpon::Application.routes.draw do

  devise_for :consortia
  devise_for :users
  devise_for :admins
  root "coupons#index"

  resources :coupons

  get "coupon_types/index" => "coupon_types#index", as: :index_coupon_type
  post "coupon_types/update" => "coupon_types#update", as: :update_coupon_type
  post "coupon_types/create" => "coupon_types#create", as: :create_coupon_type
  get "coupon_types/destroy/:id" => "coupon_types#destroy", as: :destroy_coupon_type

  get "coupon_states/index" => "coupon_states#index", as: :index_coupon_state
  post "coupon_states/update" => "coupon_states#update", as: :update_coupon_state
  post "coupon_states/create" => "coupon_states#create", as: :create_coupon_state
  get "coupon_states/destroy/:id" => "coupon_states#destroy", as: :destroy_coupon_state

  get "store_types/index" => "store_types#index", as: :index_store_type
  post "store_types/update" => "store_types#update", as: :update_store_type
  post "store_types/create" => "store_types#create", as: :create_store_type
  get "store_types/destroy/:id" => "store_types#destroy", as: :destroy_store_type

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :coupons

end

app/models/availability.rb
class Availability < ActiveRecord::Base

	belongs_to :store
	belongs_to :coupon

end

app/models/consortium.rb
class Consortium < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :stores
	has_many :coupons

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base

	belongs_to :coupon_type
	belongs_to :coupon_state
	belongs_to :consortium
	belongs_to :admin

	has_many :histories
	has_many :users, through: :histories 

	has_many :availabilities
	has_many :stores, through: :availabilities

end

app/models/coupon_state.rb
class CouponState < ActiveRecord::Base

	has_many :coupons

end

app/models/coupon_type.rb
class CouponType < ActiveRecord::Base

	has_many :coupons

end

app/models/history.rb
class History < ActiveRecord::Base

	belongs_to :user
	belongs_to :coupon	

end

app/models/store.rb
class Store < ActiveRecord::Base

	belongs_to :consortium
	belongs_to :store_type
	has_many :stores
	has_many :store_phones

	has_many :availabilities
	has_many :coupons, through: :availabilities

end

app/models/store_phone.rb
class StorePhone < ActiveRecord::Base

	belongs_to :store

end

app/models/store_type.rb
class StoreType < ActiveRecord::Base

	has_many :stores

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :histories
	has_many :coupons, through: :histories

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coupon_controller.rb
class CouponController < ApplicationController
  def index
    @coupons = Coupon.all
  end

  def show
  end

  def new
  end

  def update
  end

  def destroy
  end

  def edit
  end

  def create
  end
end

app/controllers/coupon_states_controller.rb
class CouponStatesController < ApplicationController
  
  def index
    @coupon_states = CouponState.all
  end

  def update
    @coupon_state = CouponState.find(params["update_id"])
    @coupon_state.name = params["new_name"]
    @coupon_state.save
    respond_to do |format|
      format.js
    end
  end

  def create
    @coupon_state = CouponState.new
    @coupon_state.name = params["name"]
    @coupon_state.save
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @coupon_state = CouponState.find(params[:id])
    @coupon_state.destroy
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/coupon_types_controller.rb
class CouponTypesController < ApplicationController
  
  def index
  	@coupon_types = CouponType.all
  end

  def update
  	@coupon_type = CouponType.find(params["update_id"])
  	@coupon_type.name = params["new_name"]
  	@coupon_type.save
  	respond_to do |format|
  		format.js
  	end
  end

  def create
  	@coupon_type = CouponType.new
  	@coupon_type.name = params["name"]
  	@coupon_type.save
  	respond_to do |format|
  		format.js
  	end
  end

  def destroy
    @coupon_type = CouponType.find(params[:id])
    @coupon_type.destroy
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: [:show, :edit, :update, :destroy]

  def index
  	@coupons = Coupon.all
  end

  def new
  	@coupon = Coupon.new
  end

  def create
  	@coupon = Coupon.new(coupon_params)
  	respond_to do |format|
  		if @coupon.save
  			format.html {redirect_to @coupon, notice: "Cupon creado"}
  			format.json { render action: 'show', status: :created, location: @coupon}
  		else
  			format.html {render action: 'new'}
  			format.json {render json: @coupon.errors, status: :unprocessable_entity}
  		end
  	end
  end

  def show
  end

  def edit
  end

  def update
  	respond_to do |format|
  		if @coupon.update(coupon_params)
  			format.html { redirect_to @coupon, notice: "Cupon Actualizado" }
  			format.json { head :no_content }
  		else
  			format.html { render action: 'edit' }
  			format.json { render json: @coupon.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def destroy
  	@coupon.destroy
  	respond_to do |format|
  		format.html { redirect_to coupons_path }
  		format.json { head :no_content }
  	end
  end

  private

  	def set_coupon
  		@coupon = Coupon.find(params[:id])
  	end

  	def coupon_params
  		params.require(:coupon).permit(:name)
  	end

end

app/controllers/store_types_controller.rb
class StoreTypesController < ApplicationController
  
  def index
  	@store_types = StoreType.all
  end

  def update
  	@store_type = StoreType.find(params["update_id"])
  	@store_type.name = params["new_name"]
  	@store_type.save
  	respond_to do |format|
  		format.js
  	end
  end

  def create
  	@store_type = StoreType.new
  	@store_type.name = params["name"]
  	@store_type.save
  	respond_to do |format|
  		format.js
  	end
  end

  def destroy
    @store_type = StoreType.find(params[:id])
    @store_type.destroy
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coupon_helper.rb
module CouponHelper
end

app/helpers/coupon_states_helper.rb
module CouponStatesHelper
end

app/helpers/coupon_types_helper.rb
module CouponTypesHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/store_types_helper.rb
module StoreTypesHelper
end

app/views/coupon/create.html.haml
%h1 Coupon#create
%p Find me in app/views/coupon/create.html.haml

app/views/coupon/destroy.html.haml
%h1 Coupon#destroy
%p Find me in app/views/coupon/destroy.html.haml

app/views/coupon/edit.html.haml
%h1 Coupon#edit
%p Find me in app/views/coupon/edit.html.haml

app/views/coupon/index.html.haml
%h1 Coupons

%table	
	%thead
		%tr
			%td Nombre
			%td Descripcion
			%td Fecha de Inicio
			%td Fecha de fin
			%td Descuento
			%td Tipo de Cupon
			%td Estado del cupon
	- @coupons.each do |coupon|

app/views/coupon/new.html.haml
%h1 Coupon#new
%p Find me in app/views/coupon/new.html.haml

app/views/coupon/show.html.haml
%h1 Coupon#show
%p Find me in app/views/coupon/show.html.haml

app/views/coupon/update.html.haml
%h1 Coupon#update
%p Find me in app/views/coupon/update.html.haml

app/views/coupon_states/_coupon_state_list_item.html.haml
%tr
	%td
		%span=cs.name
	%td
		%span
			=link_to "Editar", "#", class: "editCouponState", data: {id: cs.id}
	%td
		%span
			=link_to "Eliminar", destroy_coupon_state_path(cs.id), remote: :true, class: "destroyCouponState"

app/views/coupon_states/create.js.haml
$("#new_form").hide();
$("#new_form form")[0].reset();
$("#coupon_state_list tbody").append("#{j render 'coupon_state_list_item', cs: @coupon_state}");
$("#coupon_state_options").show();

app/views/coupon_states/index.html.haml
%h1 Estados de Cupones

%table#coupon_state_list
	%thead
		%tr
			%th Estado de cupon
			%th{ colspan: "2"} Opciones
	%tbody
		- @coupon_states.each do |cs|
			%tr
				= render "coupon_state_list_item", cs: cs

#coupon_state_options{ style: "padding: 10px; margin: 10px;"}
	=link_to "Crear nuevo tipo de cupon", "#", class: :new_coupon_state

#update_form{style: "display: none; padding: 10px; margin: 10px;"}
	=form_tag update_coupon_state_path, remote: :true do
		=hidden_field_tag "update_id"
		.formField
			=label_tag "new_name","Nuevo Nombre: "
			=text_field_tag "new_name"
		.formField
			=submit_tag

#new_form{style: "display: none; padding: 10px; margin: 10px;"}
	=form_tag create_coupon_state_path, remote: :true do
		.formField
			=label_tag "name", "Nombre: "
			=text_field_tag "name"
		.formField
			=submit_tag

app/views/coupon_states/update.js.haml
$(".toChange").remove();
$("#coupon_state_list tbody").append("#{j render 'coupon_state_list_item', cs: @coupon_state}");
$("#update_form form")[0].reset();
$("#update_form").hide()

app/views/coupons/_form.html.haml
=form_for(@coupon) do |f|
	- if @coupon.errors.any?
		%ul
			-@coupon.errors.full_messages.each do |msg|
				%li
					=msg
	.part
		=f.label :name
		=f.text_field :name
	.part
		=f.submit

app/views/coupons/edit.html.haml
%h1
	Editar Cupon

=render "form"

%ul
	%li
		=link_to "volver", coupons_path

app/views/coupons/index.html.haml
%h1 Coupons

%ul
	%li
		=link_to "Nuevo Cupon", new_coupon_path

%table	
	%thead
		%tr
			%td Nombre
			%td Descripcion
			%td Fecha de Inicio
			%td Fecha de fin
			%td Descuento
			%td Tipo de Cupon
			%td Estado del cupon
	%tbody
		- @coupons.each do |coupon|
			%tr
				%td 
					=link_to coupon.name, coupon

app/views/coupons/new.html.haml
%h1 Nuevo Cupon

=render "form"

%ul
	%li
		=link_to "Volver", coupons_path

app/views/coupons/show.html.haml
- unless notice.nil? || notice.empty?
	%p
		=notice

%p
	%span 
		=@coupon.name

%ul
	%li
		=link_to "Volver", coupons_path
	%li
		=link_to "Editar", edit_coupon_path(@coupon)
	%li
		=link_to "Borrar", @coupon, method: :delete, data: { confirm: "de veritaz?" }