config/routes.rb
Qpon::Application.routes.draw do

  devise_for :consortia
  devise_for :users
  devise_for :admins
  root "coupons#index"

  resources :coupons

  get "coupon_types/index" => "coupon_types#index", as: :index_coupon_type
  post "coupon_types/update" => "coupon_types#update", as: :update_coupon_type
  post "coupon_types/create" => "coupon_types#create", as: :create_coupon_type
  get "coupon_types/destroy/:id" => "coupon_types#destroy", as: :destroy_coupon_type

  get "coupon_states/index" => "coupon_states#index", as: :index_coupon_state
  post "coupon_states/update" => "coupon_states#update", as: :update_coupon_state
  post "coupon_states/create" => "coupon_states#create", as: :create_coupon_state
  get "coupon_states/destroy/:id" => "coupon_states#destroy", as: :destroy_coupon_state

  get "store_types/index" => "store_types#index", as: :index_store_type
  post "store_types/update" => "store_types#update", as: :update_store_type
  post "store_types/create" => "store_types#create", as: :create_store_type
  get "store_types/destroy/:id" => "store_types#destroy", as: :destroy_store_type

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :coupons

end

app/models/availability.rb
class Availability < ActiveRecord::Base

	belongs_to :store
	belongs_to :coupon

end

app/models/consortium.rb
class Consortium < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :stores
	has_many :coupons

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base

	belongs_to :coupon_type
	belongs_to :coupon_state
	belongs_to :consortium
	belongs_to :admin

	has_many :histories
	has_many :users, through: :histories 

	has_many :availabilities
	has_many :stores, through: :availabilities

end

app/models/coupon_state.rb
class CouponState < ActiveRecord::Base

	has_many :coupons

end

app/models/coupon_type.rb
class CouponType < ActiveRecord::Base

	has_many :coupons

end

app/models/history.rb
class History < ActiveRecord::Base

	belongs_to :user
	belongs_to :coupon	

end

app/models/store.rb
class Store < ActiveRecord::Base

	belongs_to :consortium
	belongs_to :store_type
	has_many :stores
	has_many :store_phones

	has_many :availabilities
	has_many :coupons, through: :availabilities

end

app/models/store_phone.rb
class StorePhone < ActiveRecord::Base

	belongs_to :store

end

app/models/store_type.rb
class StoreType < ActiveRecord::Base

	has_many :stores

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :histories
	has_many :coupons, through: :histories

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coupon_controller.rb
class CouponController < ApplicationController
  def index
    @coupons = Coupon.all
  end

  def show
  end

  def new
  end

  def update
  end

  def destroy
  end

  def edit
  end

  def create
  end
end

app/controllers/coupon_types_controller.rb
class CouponTypesController < ApplicationController
  
  def index
  	@coupon_types = CouponType.all
  end

  def update
  	@coupon_type = CouponType.find(params["update_id"])
  	@coupon_type.name = params["new_name"]
  	@coupon_type.save
  	respond_to do |format|
  		format.js
  	end
  end

  def create
  	@coupon_type = CouponType.new
  	@coupon_type.name = params["name"]
  	@coupon_type.save
  	respond_to do |format|
  		format.js
  	end
  end

  def destroy
    @coupon_type = CouponType.find(params[:id])
    @coupon_type.destroy
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: [:show, :edit, :update, :destroy]

  def index
  	@coupons = Coupon.all
  end

  def new
  	@coupon = Coupon.new
  end

  def create
  	@coupon = Coupon.new(coupon_params)
  	respond_to do |format|
  		if @coupon.save
  			format.html {redirect_to @coupon, notice: "Cupon creado"}
  			format.json { render action: 'show', status: :created, location: @coupon}
  		else
  			format.html {render action: 'new'}
  			format.json {render json: @coupon.errors, status: :unprocessable_entity}
  		end
  	end
  end

  def show
  end

  def edit
  end

  def update
  	respond_to do |format|
  		if @coupon.update(coupon_params)
  			format.html { redirect_to @coupon, notice: "Cupon Actualizado" }
  			format.json { head :no_content }
  		else
  			format.html { render action: 'edit' }
  			format.json { render json: @coupon.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def destroy
  	@coupon.destroy
  	respond_to do |format|
  		format.html { redirect_to coupons_path }
  		format.json { head :no_content }
  	end
  end

  private

  	def set_coupon
  		@coupon = Coupon.find(params[:id])
  	end

  	def coupon_params
  		params.require(:coupon).permit(:name)
  	end

end

app/controllers/store_types_controller.rb
class StoreTypesController < ApplicationController
  
  def index
  	@store_types = StoreType.all
  end

  def update
  	@store_type = StoreType.find(params["update_id"])
  	@store_type.name = params["new_name"]
  	@store_type.save
  	respond_to do |format|
  		format.js
  	end
  end

  def create
  	@store_type = StoreType.new
  	@store_type.name = params["name"]
  	@store_type.save
  	respond_to do |format|
  		format.js
  	end
  end

  def destroy
    @store_type = StoreType.find(params[:id])
    @store_type.destroy
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coupon_helper.rb
module CouponHelper
end

app/helpers/coupon_states_helper.rb
module CouponStatesHelper
end

app/helpers/coupon_types_helper.rb
module CouponTypesHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/store_types_helper.rb
module StoreTypesHelper
end

app/views/coupon_types/_coupon_type_list_item.html.haml
%tr
	%td
		%span=ct.name
	%td
		%span
			=link_to "Editar", "#", class: "editCouponType", data: {id: ct.id}
	%td
		%span
			=link_to "Eliminar", destroy_coupon_type_path(ct.id), remote: :true, class: "destroyCouponType"

app/views/coupon_types/_index_list_item.html.haml
%tr
	%td
		%span=ct.name
	%td
		%span
			=link_to "Editar", "#", class: "editCouponType", data: {id: ct.id}
	%td
		%span=link_to "Eliminar", "#", remote: :true

app/views/coupon_types/create.js.haml
$("#new_form").hide();
$("#new_form form")[0].reset();
$("#coupon_type_list tbody").append("#{j render 'coupon_type_list_item', ct: @coupon_type}");
$("#coupon_type_options").show();

app/views/coupon_types/index.html.haml
%h1 Tipos de Cupones

%table#coupon_type_list
	%thead
		%tr
			%th Tipo de cupon
			%th{ colspan: "2"} Opciones
	%tbody
		- @coupon_types.each do |ct|
			%tr
				= render "coupon_type_list_item", ct: ct

#coupon_type_options{ style: "padding: 10px; margin: 10px;"}
	=link_to "Crear nuevo tipo de cupon", "#", class: :new_coupon_type

#update_form{style: "display: none; padding: 10px; margin: 10px;"}
	=form_tag update_coupon_type_path, remote: :true do
		=hidden_field_tag "update_id"
		.formField
			=label_tag "new_name","Nuevo Nombre: "
			=text_field_tag "new_name"
		.formField
			=submit_tag

#new_form{style: "display: none; padding: 10px; margin: 10px;"}
	=form_tag create_coupon_type_path, remote: :true do
		.formField
			=label_tag "name", "Nombre: "
			=text_field_tag "name"
		.formField
			=submit_tag

app/views/coupon_types/update.js.haml
$(".toChange").remove();
$("#coupon_type_list tbody").append("#{j render 'coupon_type_list_item', ct: @coupon_type}");
$("#update_form form")[0].reset();
$("#update_form").hide()

app/views/store_types/_store_type_list_item.html.haml
%tr
	%td
		%span=s.name
	%td
		%span
			=link_to "Editar", "#", class: "editStoreType", data: {id: s.id}
	%td
		%span
			=link_to "Eliminar", destroy_store_type_path(s.id), remote: :true, class: "destroyStoreType"

app/views/store_types/create.js.haml
$("#new_form").hide();
$("#new_form form")[0].reset();
$("#store_type_list tbody").append("#{j render 'store_type_list_item', s: @store_type}");
$("#store_type_options").show();

app/views/store_types/index.html.haml
%h1 Tipos de Tienda

%table#store_type_list
	%thead
		%tr
			%th Tipo de tienda
			%th{ colspan: "2"} Opciones
	%tbody
		- @store_types.each do |s|
			%tr
				= render "store_type_list_item", s: s

#store_type_options{ style: "padding: 10px; margin: 10px;"}
	=link_to "Crear nuevo tipo de cupon", "#", class: :new_store_type

#update_form{style: "display: none; padding: 10px; margin: 10px;"}
	=form_tag update_store_type_path, remote: :true do
		=hidden_field_tag "update_id"
		.formField
			=label_tag "new_name","Nuevo Nombre: "
			=text_field_tag "new_name"
		.formField
			=submit_tag

#new_form{style: "display: none; padding: 10px; margin: 10px;"}
	=form_tag create_store_type_path, remote: :true do
		.formField
			=label_tag "name", "Nombre: "
			=text_field_tag "name"
		.formField
			=submit_tag

app/views/store_types/update.js.haml
$(".toChange").remove();
$("#store_type_list tbody").append("#{j render 'store_type_list_item', s: @store_type}");
$("#update_form form")[0].reset();
$("#update_form").hide()