config/routes.rb
Qpon::Application.routes.draw do

  devise_for :consortia
  devise_for :users
  devise_for :admins
  root "coupons#index"

  resources :coupons

  get "coupon_types/index" => "coupon_types#index", as: :index_coupon_type
  post "coupon_types/update" => "coupon_types#update", as: :update_coupon_type
  post "coupon_types/create" => "coupon_types#create", as: :create_coupon_type
  get "coupon_types/destroy/:id" => "coupon_types#destroy", as: :destroy_coupon_type

  get "coupon_states/index" => "coupon_states#index", as: :index_coupon_state
  post "coupon_states/update" => "coupon_states#update", as: :update_coupon_state
  post "coupon_states/create" => "coupon_states#create", as: :create_coupon_state
  get "coupon_states/destroy/:id" => "coupon_states#destroy", as: :destroy_coupon_state

  get "store_types/index" => "store_types#index", as: :index_store_type
  post "store_types/update" => "store_types#update", as: :update_store_type
  post "store_types/create" => "store_types#create", as: :create_store_type
  get "store_types/destroy/:id" => "store_types#destroy", as: :destroy_store_type

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :coupons

end

app/models/availability.rb
class Availability < ActiveRecord::Base

	belongs_to :store
	belongs_to :coupon

end

app/models/consortium.rb
class Consortium < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :stores
	has_many :coupons

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base

	belongs_to :coupon_type
	belongs_to :coupon_state
	belongs_to :consortium
	belongs_to :admin

	has_many :histories
	has_many :users, through: :histories 

	has_many :availabilities
	has_many :stores, through: :availabilities

end

app/models/coupon_state.rb
class CouponState < ActiveRecord::Base

	has_many :coupons

end

app/models/coupon_type.rb
class CouponType < ActiveRecord::Base

	has_many :coupons

end

app/models/history.rb
class History < ActiveRecord::Base

	belongs_to :user
	belongs_to :coupon	

end

app/models/store.rb
class Store < ActiveRecord::Base

	belongs_to :consortium
	belongs_to :store_type
	has_many :stores
	has_many :store_phones

	has_many :availabilities
	has_many :coupons, through: :availabilities

end

app/models/store_phone.rb
class StorePhone < ActiveRecord::Base

	belongs_to :store

end

app/models/store_type.rb
class StoreType < ActiveRecord::Base

	has_many :stores

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :histories
	has_many :coupons, through: :histories

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coupon_controller.rb
class CouponController < ApplicationController
  def index
    @coupons = Coupon.all
  end

  def show
  end

  def new
  end

  def update
  end

  def destroy
  end

  def edit
  end

  def create
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: [:show, :edit, :update, :destroy]

  def index
  	@coupons = Coupon.all
  end

  def new
  	@coupon = Coupon.new
  end

  def create
  	@coupon = Coupon.new(coupon_params)
  	respond_to do |format|
  		if @coupon.save
  			format.html {redirect_to @coupon, notice: "Cupon creado"}
  			format.json { render action: 'show', status: :created, location: @coupon}
  		else
  			format.html {render action: 'new'}
  			format.json {render json: @coupon.errors, status: :unprocessable_entity}
  		end
  	end
  end

  def show
  end

  def edit
  end

  def update
  	respond_to do |format|
  		if @coupon.update(coupon_params)
  			format.html { redirect_to @coupon, notice: "Cupon Actualizado" }
  			format.json { head :no_content }
  		else
  			format.html { render action: 'edit' }
  			format.json { render json: @coupon.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def destroy
  	@coupon.destroy
  	respond_to do |format|
  		format.html { redirect_to coupons_path }
  		format.json { head :no_content }
  	end
  end

  private

  	def set_coupon
  		@coupon = Coupon.find(params[:id])
  	end

  	def coupon_params
  		params.require(:coupon).permit(:name)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coupon_helper.rb
module CouponHelper
end

app/helpers/coupon_states_helper.rb
module CouponStatesHelper
end

app/helpers/coupon_types_helper.rb
module CouponTypesHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/store_types_helper.rb
module StoreTypesHelper
end

app/views/layouts/_navigation_bar.html.haml
%ul
	%li
		=link_to "Inicio", root_path
	%li
		=link_to "Cupones", coupons_path
	%li
		=link_to "Tipo de Cupones", index_coupon_type_path
	%li
		=link_to "Estado del cupon",  index_coupon_state_path
	%li
		=link_to "Tipo de Tiendas", index_store_type_path
	%li
		=link_to "Tiendas", "#"

#consortia
	%h2	Consorcios
	%ul
		-if consortium_signed_in?
			%li
				= link_to "(Consorcio) Editar perfil", edit_consortium_registration_path
			%li
				= link_to "(Consorcio) Cerrar sesion", destroy_consortium_session_path, method: :delete
		-else
			%li
				= link_to "(Consorcio) Registrarse", new_consortium_registration_path
			%li
				= link_to "(Consorcio) Iniciar Sesion", new_consortium_session_path

#admins
	%h2	Administradores
	%ul
		-if admin_signed_in?
			%li
				= link_to "(Administrador) Editar perfil", edit_admin_registration_path
			%li
				= link_to "(Administrador) Cerrar sesion", destroy_admin_session_path, method: :delete
		-else
			%li
				= link_to "(Administrador) Registrarse", new_admin_registration_path
			%li
				= link_to "(Administrador) Iniciar Sesion", new_admin_session_path

#users
	%h2 Usuarios
	%ul
		-if user_signed_in?
			%li
				= link_to "Editar perfil", edit_user_registration_path
			%li
				= link_to "Cerrar sesion", destroy_user_session_path, method: :delete
		-else
			%li
				= link_to "Registrarse", new_user_registration_path
			%li
				= link_to "Iniciar Sesion", new_user_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qpon</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!DOCTYPE 5
%html{ lang: "en"}
	%head
		= stylesheet_link_tag "application", media: "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
	%body
		#navbar
			= render "layouts/navigation_bar"
		#content
			= yield